### ISSUE TITLE
Review and update YARN SPI reference guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-yarn#10]
As a developer, I'd like to review and update YARN SPI deployer section(s) in the reference guide

**Comment by trisberg** [comment]
The docs are actually in the `spring-cloud-spring-cloud-dataflow` project and the whole "Getting Started" section needs a refresh. Also, we don't have a snapshot build for this project yet, so can test any new instructions yet. Putting this on hold for now.

**Comment by trisberg** [comment]
Moved all SPI documentation tasks to https://github.com/spring-cloud/spring-cloud-dataflow/issues/200
