### ISSUE TITLE
flo for Spring Cloud Data flow Yarn is not working

### ISSUE THREAD

**Issue by pradbit** [spring-cloud/spring-cloud-dataflow-admin-yarn#101]
Hi,

I downloaded the latest release 1.0.0.M2 of Spring Cloud Data flow Yarn SPI and built it using the standard mvn clean package command. The built environment is Hortonworks Sandbox 2.4 on a standalone machine. I have seen the server yarn jar created in the regular target folder and also the distribution is created in the spring-cloud-dataflow-server-yarn-dist folder. As I would use the script "dataflow-server-yarn" to start the server because it is setting some environment variables, I patched the "spring-cloud-dataflow-server-yarn-1.0.0.M2.jar" file present in the lib folder of the distribution folder for using flo. This is because the server script is invoking the jar from the lib folder. But it is not showing the Create stream options in the admin-ui. I first used the flo 1.0.0.M2 as the server-yarn is of that version and also later tried with flo 1.0.0.M3. Please clarify.

However, flo is working properly as expected with the local SPI implementation.

**Comment by sabbyanandan** [comment]
Hi, @pradbit:

Thanks for reporting this.

1.0.0.M2 release of SCDF's YARN server is compatible only with 1.0.0.M3 release of Flo. Perhaps the [compatibility matrix](http://cloud.spring.io/spring-cloud-dataflow/) in the project site could be useful.

With that said, could you please confirm that you followed the installation steps as described in the docs [here](http://docs.pivotal.io/spring-cloud-data-flow/installing-scdf.html)?

**Comment by sabbyanandan** [comment]
I also tried it locally with the latest from `master`and Flo comes up fine. The key is to make sure you unpack the Flo ZIP (`/lib` folder) under `spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib` and you patch it from this directory.

![image](https://cloud.githubusercontent.com/assets/1562654/15342094/b39b4610-1c47-11e6-918c-2c59c6573d05.png)

**Comment by pradbit** [comment]
Hi @sabbyanandan 

I tried with yarn release 1.0.0.M2 earlier and tried with the master snapshot just now as you did...Please see the below steps followed. Flo is still not showing up. Not sure if there is anything related to environment which I need to take care of. But as said, it was working when the local SPI was deployed and yarn created issues...

[root@sandbox SCDF_Yarn_New]# git clone https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn.git
Cloning into 'spring-cloud-dataflow-server-yarn'...
remote: Counting objects: 1404, done.
remote: Total 1404 (delta 0), reused 0 (delta 0), pack-reused 1404
Receiving objects: 100% (1404/1404), 336.72 KiB | 241.00 KiB/s, done.
Resolving deltas: 100% (430/430), done.
Checking connectivity... done.

[root@sandbox SCDF_Yarn_New]# cd spring-cloud-dataflow-server-yarn

[root@sandbox spring-cloud-dataflow-server-yarn]# ls -la

total 84
drwxr-xr-x 11 root root 4096 2016-05-18 05:21 .
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 ..
drwxr-xr-x  7 root root 4096 2016-05-18 05:21 .git
-rw-r--r--  1 root root  464 2016-05-18 05:21 .gitignore
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 .mvn
-rw-r--r--  1 root root 7330 2016-05-18 05:21 mvnw
-rw-r--r--  1 root root 7330 2016-05-18 05:21 mvnw.cmd
-rw-r--r--  1 root root 5002 2016-05-18 05:21 pom.xml
-rw-r--r--  1 root root 3795 2016-05-18 05:21 README.adoc
-rw-r--r--  1 root root 1580 2016-05-18 05:21 .settings.xml
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn-autoconfig
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn-client
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn-dist
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn-docs
drwxr-xr-x  3 root root 4096 2016-05-18 05:21 spring-cloud-dataflow-server-yarn-h2
drwxr-xr-x  2 root root 4096 2016-05-18 05:21 spring-cloud-starter-dataflow-server-yarn
-rw-r--r--  1 root root  399 2016-05-18 05:21 .travis.yml

[root@sandbox spring-cloud-dataflow-server-yarn]# mvn clean package

After the build is successful...used the below commands...

[root@sandbox spring-cloud-dataflow-server-yarn]# pwd
/root/pradeep/SCDF_Yarn_New/spring-cloud-dataflow-server-yarn

[root@sandbox spring-cloud-dataflow-server-yarn]# cd /root/pradeep/SCDF_Yarn_New/spring-cloud-dataflow-server-yarn/spring-cloud-dataflow-server-yarn-dist/target

[root@sandbox target]# ls -la
total 282116
drwxr-xr-x 4 root root      4096 2016-05-18 06:01 .
drwxr-xr-x 4 root root      4096 2016-05-18 06:00 ..
drwxr-xr-x 2 root root      4096 2016-05-18 06:00 archive-tmp
-rw-r--r-- 1 root root 288868811 2016-05-18 06:01 spring-cloud-dataflow-server-yarn-dist-1.0.0.BUILD-SNAPSHOT.zip
drwxr-xr-x 4 root root      4096 2016-05-18 06:00 staging

[root@sandbox target]# unzip spring-cloud-dataflow-server-yarn-dist-1.0.0.BUILD-SNAPSHOT.zip
Archive:  spring-cloud-dataflow-server-yarn-dist-1.0.0.BUILD-SNAPSHOT.zip
   creating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/
   creating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/bin/
   creating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/config/
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-server-yarn-cli
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-server-yarn-h2
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-server-yarn
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/bin/dataflow-shell
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/config/hdfs-applications.properties
  inflating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/config/servers.yml
   creating: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-dataflow-shell-1.0.0.M3.jar
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-dataflow-server-yarn-h2-1.0.0.BUILD-SNAPSHOT.jar
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-deployer-yarn-appdeployerappmaster-1.0.0.M1.jar
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-deployer-yarn-tasklauncherappmaster-1.0.0.M1.jar
 extracting: spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT/lib/spring-cloud-dataflow-server-yarn-client-1.0.0.BUILD-SNAPSHOT.jar

[root@sandbox target]# ls -la
total 282120
drwxr-xr-x 5 root root      4096 2016-05-18 06:11 .
drwxr-xr-x 4 root root      4096 2016-05-18 06:00 ..
drwxr-xr-x 2 root root      4096 2016-05-18 06:00 archive-tmp
drwxr-xr-x 5 root root      4096 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT
-rw-r--r-- 1 root root 288868811 2016-05-18 06:01 spring-cloud-dataflow-server-yarn-dist-1.0.0.BUILD-SNAPSHOT.zip
drwxr-xr-x 4 root root      4096 2016-05-18 06:00 staging

[root@sandbox target]# cd spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT

[root@sandbox spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT]# ls -la
total 20
drwxr-xr-x 5 root root 4096 2016-05-18 06:00 .
drwxr-xr-x 5 root root 4096 2016-05-18 06:11 ..
drwxr-xr-x 2 root root 4096 2016-05-18 06:00 bin
drwxr-xr-x 2 root root 4096 2016-05-18 06:00 config
drwxr-xr-x 2 root root 4096 2016-05-18 06:01 lib

Going into the lib folder now...

[root@sandbox spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT]# cd lib

[root@sandbox lib]# ls -la
total 282104
drwxr-xr-x 2 root root     4096 2016-05-18 06:01 .
drwxr-xr-x 5 root root     4096 2016-05-18 06:00 ..
-rw-r--r-- 1 root root 81322700 2016-05-18 05:59 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 61842305 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-client-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root  8670143 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-h2-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 16819438 2016-05-18 05:58 spring-cloud-dataflow-shell-1.0.0.M3.jar
-rw-r--r-- 1 root root 60100281 2016-05-18 05:51 spring-cloud-deployer-yarn-appdeployerappmaster-1.0.0.M1.jar
-rw-r--r-- 1 root root 60100325 2016-05-18 05:51 spring-cloud-deployer-yarn-tasklauncherappmaster-1.0.0.M1.jar

Transferred the flo-spring-cloud-dataflow-ui-1.0.0.M3.zip to the above folder now and unzipped it there...

[root@sandbox lib]# ls -la
total 286768
drwxr-xr-x 3 root root     4096 2016-05-18 06:12 .
drwxr-xr-x 5 root root     4096 2016-05-18 06:00 ..
-rw-r--r-- 1 root root  4771410 2016-05-05 09:59 flo-spring-cloud-dataflow-ui-1.0.0.M3.zip
drwxr-xr-x 2 root root     4096 2016-04-29 18:48 lib
-rw-r--r-- 1 root root 81322700 2016-05-18 05:59 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 61842305 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-client-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root  8670143 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-h2-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 16819438 2016-05-18 05:58 spring-cloud-dataflow-shell-1.0.0.M3.jar
-rw-r--r-- 1 root root 60100281 2016-05-18 05:51 spring-cloud-deployer-yarn-appdeployerappmaster-1.0.0.M1.jar
-rw-r--r-- 1 root root 60100325 2016-05-18 05:51 spring-cloud-deployer-yarn-tasklauncherappmaster-1.0.0.M1.jar

[root@sandbox lib]# ls -l lib
total 5160
-rw-r--r-- 1 root root 5281658 2016-04-29 18:47 spring-cloud-dataflow-ui-1.0.0.M3.jar

Taking the backup of the original Server JAR file...

[root@sandbox lib]# cp spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar.orig

[root@sandbox lib]# ls -la
total 366188
drwxr-xr-x 3 root root     4096 2016-05-18 06:13 .
drwxr-xr-x 5 root root     4096 2016-05-18 06:00 ..
-rw-r--r-- 1 root root  4771410 2016-05-05 09:59 flo-spring-cloud-dataflow-ui-1.0.0.M3.zip
drwxr-xr-x 2 root root     4096 2016-04-29 18:48 lib
-rw-r--r-- 1 root root 81322700 2016-05-18 05:59 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 81322700 2016-05-18 06:13 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar.orig
-rw-r--r-- 1 root root 61842305 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-client-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root  8670143 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-h2-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 16819438 2016-05-18 05:58 spring-cloud-dataflow-shell-1.0.0.M3.jar
-rw-r--r-- 1 root root 60100281 2016-05-18 05:51 spring-cloud-deployer-yarn-appdeployerappmaster-1.0.0.M1.jar
-rw-r--r-- 1 root root 60100325 2016-05-18 05:51 spring-cloud-deployer-yarn-tasklauncherappmaster-1.0.0.M1.jar

Renaming the ui JAR to match the server JAR version which is build snapshot...

[root@sandbox lib]# mv lib/spring-cloud-dataflow-ui-1.0.0.M3.jar lib/spring-cloud-dataflow-ui-1.0.0.BUILD-SNAPSHOT.jar

[root@sandbox lib]# ls -l lib
total 5160
-rw-r--r-- 1 root root 5281658 2016-04-29 18:47 spring-cloud-dataflow-ui-1.0.0.BUILD-SNAPSHOT.jar

Patching the JAR file now...

[root@sandbox lib]# jar -u0vf spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar lib
adding: lib/(in = 0) (out= 0)(stored 0%)
adding: lib/spring-cloud-dataflow-ui-1.0.0.BUILD-SNAPSHOT.jar(in = 5281658) (out= 5281658)(stored 0%)

[root@sandbox lib]# ls -la
total 371344
drwxr-xr-x 3 root root     4096 2016-05-18 06:15 .
drwxr-xr-x 5 root root     4096 2016-05-18 06:00 ..
-rw-r--r-- 1 root root  4771410 2016-05-05 09:59 flo-spring-cloud-dataflow-ui-1.0.0.M3.zip
drwxr-xr-x 2 root root     4096 2016-05-18 06:14 lib
-rw------- 1 root root 86604650 2016-05-18 06:15 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 81322700 2016-05-18 06:13 spring-cloud-dataflow-server-yarn-1.0.0.BUILD-SNAPSHOT.jar.orig
-rw-r--r-- 1 root root 61842305 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-client-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root  8670143 2016-05-18 06:00 spring-cloud-dataflow-server-yarn-h2-1.0.0.BUILD-SNAPSHOT.jar
-rw-r--r-- 1 root root 16819438 2016-05-18 05:58 spring-cloud-dataflow-shell-1.0.0.M3.jar
-rw-r--r-- 1 root root 60100281 2016-05-18 05:51 spring-cloud-deployer-yarn-appdeployerappmaster-1.0.0.M1.jar
-rw-r--r-- 1 root root 60100325 2016-05-18 05:51 spring-cloud-deployer-yarn-tasklauncherappmaster-1.0.0.M1.jar

The patched JAR is now of size 86604650 and the original is 81322700

**Comment by pradbit** [comment]
Hi @sabbyanandan 

I'm able to bring up the Flo 1.0.0.M3 for yarn release 1.0.0.M2, but it is peculiar. The Step 6 provided in the Flo install instructions ($ mv lib/spring-cloud-dataflow-ui-[DOWNLOADED_VERSION].jar lib/spring-cloud-dataflow-ui-[BUILT_VERSION].jar) is bringing the difference. It is working if I DON'T rename it to be in sync with the Yarn version. Here it is

Before Patch: server yarn file bytes in the lib folder are 81322515

-rw------- 1 root root 81322515 2016-05-18 12:46 spring-cloud-dataflow-server-yarn-1.0.0.M2.jar

As the yarn version is 1.0.0.M2, renamed the Flo file to "spring-cloud-dataflow-ui-1.0.0.M2.jar" from "spring-cloud-dataflow-ui-1.0.0.M3.jar"

After Patch: server yarn file bytes in the lib folder are 86604441

-rw------- 1 root root 86604441 2016-05-18 12:45 spring-cloud-dataflow-server-yarn-1.0.0.M2.jar

This process is not bringing up the Flo.

**Working Steps:**

Before Patch: server yarn file bytes in the lib folder are 81322515

-rw------- 1 root root 81322515 2016-05-18 12:46 spring-cloud-dataflow-server-yarn-1.0.0.M2.jar

NO RENAME APPLIED AS ABOVE and directly patched "spring-cloud-dataflow-ui-1.0.0.M3.jar" to "spring-cloud-dataflow-server-yarn-1.0.0.M2.jar"

After Patch: server yarn file bytes in the lib folder are 84450707 and Flo working

-rw------- 1 root root 84450707 2016-05-18 12:47 spring-cloud-dataflow-server-yarn-1.0.0.M2.jar

This is making the Flo work and if you observe, the file bytes are "84450707" now which is not the case when the rename is applied "86604441"

**Comment by sabbyanandan** [comment]
Thanks for the details! We are in the process of [merging Flo](https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/50) into the core dataflow-ui project, so all these extra steps wouldn't be necessary with the upcoming RC release. In the meantime, we will verify and update the docs. 

If you see any other issues, feel free to open a new ticket.
