### ISSUE TITLE
Add CI pipeline for SCDF-Admin-YARN

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-yarn#11]
As a developer, I'd like to create separate CI pipeline for _YARN_ SPI, so I can run incremental builds and validate SCDF features.

**Acceptance:**
- Bamboo infrastructure for YARN SPI is created
- Unit / Integration tests are included in CI plan

**Comment by jvalkeal** [comment]
Btw, I don't have rights to create anything under https://build.spring.io/browse/SCD.

**Comment by sabbyanandan** [comment]
@markpollack / @trevormarshall could help us here.

**Comment by trevormarshall** [comment]
Added Sabby and Janne to each of those plans.
