### ISSUE TITLE
Create a shell project that adds core commands in addition to hadoop specific commands.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-admin-yarn#118]

**Comment by jvalkeal** [comment]
@markpollack Quickly looked at this and realised that `spring-cloud-dataflow-shell` is a fatjar, thus making it impossible to extend that. I think we need to move stuff from shell into `spring-cloud-dataflow-shell-core` while keeping `spring-cloud-dataflow-shell` as fatjar generating project. Then I think I can do `spring-cloud-dataflow-server-yarn-shell`, depend on `spring-cloud-dataflow-shell-core` and do my own packaging with hdfs related commands.

Though it may be that `spring-cloud-dataflow-shell.jar` will work but it's a little awkward to have one fatjar inside other fatjar. I don't even know how boot handles that.
