### ISSUE TITLE
Adapt to latest SCDF docs

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-admin-yarn#143]
see https://github.com/spring-cloud/spring-cloud-dataflow/pull/965/files?diff=unified#r85108779

(should only be merged once this server project depends on a post-M1-fixed version of SCDF)

**Comment by jvalkeal** [comment]
Moving this away from RC1 as existing stuff we should include contains refs to local server and shell. If docs are fixed for core RELEASE then we can include those to yarn RELEASE.
