### ISSUE TITLE
Get ExecutionId for Composed Task from subtasks

### ISSUE THREAD

**Issue by mygordienko** [spring-cloud/spring-cloud-dataflow-admin-yarn#172]
Hello!
I thinks it should be possible to get executionId for parent task (composed task) from within subtasks,
For example subtasks might produce different results, but all of them are connected logicaly and User might want to get any of them after task is done. So I thought that such relation could be implemented if subtasks have access to parent executionID.

I asked this here as well:
https://stackoverflow.com/questions/48824165/spring-cloud-task-get-executionid-for-composed-task

**Comment by cppwfs** [comment]
Just created a issue on the Composed-Task-Runner issues to handle this.  The issue can be found here: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/28
