### ISSUE TITLE
Problem with creating composed taks.

### ISSUE THREAD

**Issue by StanislavSerdiuk** [spring-cloud/spring-cloud-dataflow-admin-yarn#173]
Hello.
I have a problem when trying to create composed task, as shown below:
![image](https://user-images.githubusercontent.com/36954138/36844079-443c7de8-1d62-11e8-8fb4-124e1f337692.png)

I get generated defenition for composed task: 
demoTask 'COMPLETED'->**demoTask1** 'FAILED'->demoTask3 && **demoTask1** && demoTask2.
After pushing button "Create", I get error "duplicate app name. Use a label to ensure uniqueness".
Let's adding lables: demoTask 'COMPLETED'->**lable1:demoTask1** 'FAILED'->demoTask3 && **lable2:demoTask1** && demoTask2. 
And we will get graph as shown below: 
![image](https://user-images.githubusercontent.com/36954138/36844416-b6b86f02-1d63-11e8-82ba-34ca841e677f.png)

As we can see graphs completely different and other attempts to shift componets are wrong too. I can not create composed task that i want initially.
Is it possible to do this? My goal is to execute some sequence of tasks after "Transition" block.

**Comment by cppwfs** [comment]
In this case the 3rd graph works as expected with Composed Tasks.   However I do see what you are saying.  So for this I created the issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2077 that will modify the syntax to support a way to resolve the issue you presented.
