### ISSUE TITLE
Make appmaster ip discovery better

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-admin-yarn#35]
Instead of using a static method to find ip to connect to, make this a configurable bean which user can setup. This would then help to find ip from multiple nics, etc.

**Comment by trisberg** [comment]
This issue prevents me from running against a YARN cluster with multiple network adapters configured

**Comment by jvalkeal** [comment]
Closing as invalid per SHDP-546. I'm gonna create a new gh issue to fix this and remove other temp tweaks from dataflow yarn.
