### ISSUE TITLE
Add a DataSource for the task database

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-yarn#49]
The spring-cloud-dataflow-admin-starter now creates the task database tables on start-up. All SPI implementations should add a DataSource to their configuration to be used for the tasks.

**Comment by jvalkeal** [comment]
Is this just what were added to `spring-cloud-dataflow-admin-local/src/main/resources/admin.yml`?

**Comment by cppwfs** [comment]
We should only need to update the admin.yml in spring-cloud-dataflow-admin-yarn.
