### ISSUE TITLE
Bundle h2 db

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-admin-yarn#58]
As a user I'd like to have usual easy way to start h2 db instead of running as embedded within admin server. This is needed for ambari work, not to use mem based and when we eventually get support running multiple admins.

**Comment by trisberg** [comment]
All you really need is a one line command to start the TCP server:

```
java -cp h2*.jar org.h2.tools.Server -tcp -tcpAllowOthers -tcpPort 19092
```

Then the database files are created based on the URL used to connect like:

```
jdbc:h2:tcp://<host>:19092//var/lib/h2/dataflow
```

So, not sure we need anything more elaborate for this.

**Comment by trisberg** [comment]
We might also consider using the following options to lock things down a bit:

```
-baseDir /var/lib/h2 -ifExists
```

but that would require that we create the database file during installation if it doesn't exist.
