### ISSUE TITLE
Document Task support in YARN deployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-yarn#7]
As a user, I'd want to refer to documentation on how to launch a task in `YARN`, so I can adapt to best practices while developing and deploying.

**Docs to include:**
- how to launch tasks from shell
- how to verify tasks running on a YARN cluster
- what are some of the monitoring and remote management capabilities 
- does ambari plugin provide task metrics

**Comment by trisberg** [comment]
Why is this specific to YARN? Wouldn't this work the same way across SPIs?

**Comment by sabbyanandan** [comment]
Agreed. This is needed across all the SPIs. Should we move it to SCDF core, instead?

**Comment by trisberg** [comment]
Is this "how to launch a task from the shell?" or more a guide to develop a task module?

**Comment by sabbyanandan** [comment]
Task support is only available with YARN deployer (_for M3_). Acceptance criteria is updated to reflect what's expected as part of the documentation. I'm hoping we could leverage some of this docs across all the deployers, as we add support for it.

**Comment by sabbyanandan** [comment]
@jvalkeal pushed doc changes.
