### ISSUE TITLE
Updated docs to reflect new repo name changes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-yarn#90]
As a developer, I'd like to rename the repo from `spring-cloud-dataflow-admin-yarn` to `spring-cloud-dataflow-server-yarn`.

**Comment by jvalkeal** [comment]
Repo rename is ok, it's just docs.

**Comment by sabbyanandan** [comment]
@jvalkeal pushed doc changes.
